# Generated by Django 4.2.9 on 2024-02-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100)),
                ('keyboard', models.CharField(max_length=100)),
                ('monitor', models.CharField(max_length=100)),
            ],
        ),
    ]
